export const rules = [
  "Site rules are non negotiable, failure to comply will result in an account termination.",
  "Site rules are valid site wide, this includes the shout box. Failure to comply will result in an account termination.",
  "Attempting any malicious activity towards this board will result in an account termination.",
  "Advertising a different community / board is prohibited, doing so will result in an account termination.",
  "Fraudulent activities such as carding is strictly prohibited, resulting in a permanent account termination.",
  "Doxing or trying to gather personal information with the intent to harm other members is prohibited, doing so will lead to an account termination.",
  "Attempting to infect or steal from other members is prohibited, doing so will lead to a permanent account termination.",
  "Engaging in threatening/insulting behaviour towards other members is prohibited, doing so will lead to a 7 day suspension.",
  "Abusing the report function will be punished via a warning to a 3 day posting & shout box suspension.",
  "Multi-accounting or account sharing is strictly prohibited, each member is limited to a single account. Create multiple accounts will void your ability to appeal a ban.",
  "Abusing the any stat system, likes,reputation,vouches system is prohibited, this includes activities such as trading or demanding likes/reputation/vouches/any stats. Doing so will result in a temporary suspension and getting your likes wiped.",
  "Using BB-Codes in the shoutbox is prohibited. Doing so might result in a temporary ban.",
  "Posting or using the shoutbox while being on a temporary account to appeal your ban will lead to a permanent ban.",
  "We reserve the right to disable your auth key if we discover any abusive behavior or usage without any further notice.",
  "Do not use BB-Codes on titles, doing so will result in a punishment.",
  "Posting referral/affiliate links without including a non-referral/non-affiliate link is forbidden. Doing so will result in a punishment.",
  "Do not beg for any kind of donations. Doing so will result in a punishment.",
  "When making giveaways, you must pick the winner in reasonable time (24h - 7 days) and give the winner a reasonable time to claim the price(eg. 24 hours).",
  "Posting on a scam report you are not directly involved in will receive a warning. Continuing to do so will result in a temporary suspension. ",
  "Selling a custom usergroup and/or ownership of a custom group to another forum member is prohibited.",
]
